postsubmits:
  iamsubratp/osconfig:
  - name: osconfig-build
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["subratp-project-2", "us-west1-a", "./packaging/build_packages_wf.json", "gs://osconfig-agent-package/"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
    max_concurrency: 10
    branches:
    - ^master$

presubmits:
  iamsubratp/osconfig:
  - name: osconfig-presubmit-build
    run_if_changed: ".*/packaging/.*"
    trigger: "(?m)^/packagebuild$"
    rerun_command: "c"
    context: prow/presubmit/packagebuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/daisy-builder:latest
        command:
        - "/main.sh"
        args: ["subratp-project-2", "us-west1-a", "./packaging/build_packages_wf.json"]
        volumeMounts:
        - name: daisy-service-account
          mountPath: /etc/daisy-service-account
          readOnly: true
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/daisy-service-account/creds.json
      volumes:
      - name: daisy-service-account
        secret:
          secretName: daisy-service-account
  - name: osconfig-presubmit-gocheck
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gocheck$"
    rerun_command: "/gocheck"
    context: prow/presubmit/gocheck
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gocheck:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gobuild
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gobuild$"
    rerun_command: "/gobuild"
    context: prow/presubmit/gobuild
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gobuild:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
  - name: osconfig-presubmit-gotest
    run_if_changed: ".*\\.go$"
    trigger: "(?m)^/gotest$"
    rerun_command: "/gotest"
    context: prow/presubmit/gotest
    decorate: true
    spec:
      containers:
      - image: gcr.io/gcp-guest/gotest:latest
        imagePullPolicy: Always
        command:
        - "/go/main.sh"
        volumeMounts:
        - name: codecov
          mountPath: /etc/codecov
          readOnly: true
      volumes:
      - name: codecov
        secret:
          secretName: codecov
